### ISSUE TITLE
how to delete partial session

### ISSUE THREAD

**Issue by fangyuan** [Wu-Wu/Dancer-Session-Redis#4]
such case: after user sign in, set sessions: `username`/`has_signed_in`.
 When after user logout, I want remove `has_signed_in` tag in session,  but keep `username` in session and do not destroy session.
It seems this module does not support function that delete partial session(s).
Any help or suggestion? Thanks.

**Comment by Wu-Wu** [comment]
Yes, it is. The module utilizes the API of the `Dancer::Session::Abstract`. The API expects on call of the method `destroy()` - current session will be deleted from storage. So if you call `session->destroy()` on logout the entire session will be deleted by its `id`.

AFAIK, there is no session backend that supported partial delete of the session on `destroy()`. The `id` is pretty much random, so no chances to get the same `id` on `create()` and resume the partially deleted session. Even too, the session data might be already flushed by redis-server (storage) - each session key creates with expiration time.
